name: Airflow CI/CD on Self-Hosted Runner

on:
  push:
    branches:
      - ci-cd-test 

env:
  # THAY THẾ BẰNG TÊN IMAGE VÀ DOCKER COMPOSE FILE CỦA BẠN
  IMAGE_NAME: elliana2811/car_detection
  DOCKER_COMPOSE_FILE: docker-compose.prod.yml # Tên file docker-compose trong repo

jobs:
  build-and-push-image:
    name: Build and Push Airflow Docker Image
    runs-on: ubuntu-latest # <<---- THAY ĐỔI Ở ĐÂY
    # ... (phần còn lại của job build-and-push-image giữ nguyên) ...
    outputs:
      image_tag_sha: ${{ steps.meta.outputs.version }} 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 # Cân nhắc nâng cấp lên v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2 # Cân nhắc nâng cấp lên v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix=,suffix=,format=short 
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        id: build_and_push
        uses: docker/build-push-action@v6
        with:
          context: ./data_pipeline/flow 
          file: ./data_pipeline/flow/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha 
          cache-to: type=gha,mode=max 

  deploy-airflow:
    name: Deploy Airflow Services
    runs-on: self-hosted # Chạy trên cùng self-hosted runner (nơi triển khai Airflow)
    needs: build-and-push-image # Chạy sau khi job build-and-push-image hoàn thành
    
    steps:
      - name: Checkout Repository (để có docker-compose.yaml)
        uses: actions/checkout@v4

      # (TÙY CHỌN) Tạo file .env từ GitHub Secret nếu cần
      # - name: Create .env file from secret
      #   if: secrets.ENV_FILE_CONTENT
      #   run: echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
      #   shell: pwsh # Sử dụng pwsh hoặc powershell cho Windows

      - name: Ensure .env file exists
        run: |
          # Sử dụng cú pháp PowerShell để kiểm tra file
          $envFilePath = ".env" # Đường dẫn tương đối đến file .env
          # Kiểm tra xem tệp có tồn tại và là một tệp tin (không phải thư mục)
          if (-not (Test-Path $envFilePath -PathType Leaf)) { 
            Write-Error "ERROR: .env file not found at '$($envFilePath)' in the checkout directory (current directory: $(Get-Location))."
            Write-Host "Please ensure the .env file with necessary configurations (especially AIRFLOW__CORE__FERNET_KEY)"
            Write-Host "is manually placed in the root of the checked-out repository on the self-hosted runner."
            exit 1 # Thoát với mã lỗi để job thất bại
          } else {
            Write-Host ".env file found at '$($envFilePath)'."
          }
        shell: powershell # Đảm bảo shell là powershell (hoặc pwsh nếu PowerShell Core đã được cài và trong PATH)

      - name: Pull latest pushed image
        # Sử dụng tag 'latest' để đơn giản hóa việc kéo image mới nhất
        # Nhớ kiểm tra lại logic tag 'latest' với nhánh default của bạn
        run: docker pull ${{ env.IMAGE_NAME }}:latest 
        shell: powershell # Thêm shell cho nhất quán, mặc dù docker pull chạy tốt trên các shell

      - name: Restart Airflow services using Docker Compose
        run: |
          Write-Host "Restarting Airflow services with the new image..."
          # Đảm bảo docker-compose.yaml đã được cập nhật để sử dụng image từ registry
          docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} up -d --remove-orphans airflow-webserver airflow-scheduler airflow-init
          Write-Host "Airflow services deployment attempted."
        shell: powershell # Thêm shell cho nhất quán