name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Airflow image
      run: |
        docker build -t elliana2811/airflow:data_pipeline ./data_pipeline
        docker push elliana2811/airflow:data_pipeline

    - name: Build and push Streamlit image
      run: |
        docker build -t elliana2811/streamlit:serving_pipeline .e/serving_pipeline
        docker push elliana2811/streamlit:serving_pipeline

    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > key.pem
        chmod 600 key.pem
        ssh -o StrictHostKeyChecking=no -i key.pem user@yourserver.com '
          cd /data_pipeline/flow &&
          docker-compose pull &&
          docker-compose up -d --build
        '
